const dataBase = [
  {
    id: 1,
    url: "https://catalogo-web.github.io/catalogo-petulap/",
    title: "Venta de Laptops",
    description: "Catalogo para la venta de laptop",
    category: "Real Projects",
    github: "https://github.com/catalogo-web/catalogo-petulap",
    language: [
      { icon: "icon-html", name: "HTML" },
      { icon: "icon-css", name: "CSS" },
      { icon: "icon-js", name: "JS" },
    ],
  },
  {
    id: 2,
    url: "https://mariaknoll.website/",
    title: "mariaknoll.website",
    description: "Catalogo full stack para vestido de fiesta",
    category: "Real Projects",
    github: "https://github.com/buchervanesa/mariaknoll.website",
    language: [
      { icon: "icon-html", name: "HTML" },
      { icon: "icon-css", name: "CSS" },
      { icon: "icon-js", name: "JavaScript" },
      { icon: "icon-nodejs", name: "Node JS" },
      { icon: "icon-mongodb", name: "MongoDB" },
    ],
  },
  {
    id: 3,
    url: "https://webpt19b.web.app/checkpoint",
    title: "Simulacro Checkpoint",
    description: "Simulacro para el checkpoin de SoyHenry",
    category: "Real Projects",
    language: [
      { icon: "icon-html", name: "HTML" },
      { icon: "icon-css", name: "CSS" },
      { icon: "icon-js", name: "JavaScript" },
    ],
  },
  {
    id: 4,
    url: "https://foudetoi.rest/",
    title: "Fou De Toi Restaurant",
    description: "Restaurante vegetariano",
    category: "Real Projects",
    language: [
      { icon: "icon-html", name: "HTML" },
      { icon: "icon-css", name: "CSS" },
      { icon: "icon-js", name: "JavaScript" },
    ],
  },
  {
    id: 5,
    url: "https://enyeinnovation.github.io/illustrator/",
    title: "illustrator",
    description: "landing Pages Responsive con HTML y CSS",
    category: "Real Projects",
    github: "https://github.com/enyeinnovation/illustrator",
    language: [
      { icon: "icon-html", name: "HTML" },
      { icon: "icon-css", name: "CSS" },
      { icon: "icon-js", name: "JavaScript" },
    ],
  },
  {
    id: 6,
    url: "https://frankgp.com/app/color/",
    title: "Color Hex",
    description: "App Generator Color Hex",
    category: "Tools",
    github: "https://frankgp.com/app/color/",
    language: [
      { icon: "icon-html", name: "HTML" },
      { icon: "icon-css", name: "CSS" },
      { icon: "icon-js", name: "JavaScript" },
    ],
  },
  {
    id: 7,
    url: "https://frankgp.com/app/mini-postman/",
    title: "Mini-Postman App",
    description: "App Mini-Postman for Get Post and Put Request",
    category: "Tools",
    github: "https://frankgp.com/app/mini-postman/",
    language: [
      { icon: "icon-html", name: "HTML" },
      { icon: "icon-css", name: "CSS" },
      { icon: "icon-js", name: "JavaScript" },
    ],
  },
];
